### ISSUE TITLE
.a文件

### ISSUE THREAD

**Issue by LqNoob** [andyweiqiu/SpeechRecognition#1]
你好！可以参考一下你的静态库(.a)文件吗？
 谢谢啊！

**Comment by andyweiqiu** [comment]
> 你好！可以参考一下你的静态库(.a)文件吗？
> 谢谢啊！

你是想要参考源代码吗？

**Comment by LqNoob** [comment]
> > 你好！可以参考一下你的静态库(.a)文件吗？
> > 谢谢啊！
> 
> 你是想要参考源代码吗？

嗯嗯，是的，目前我也在做这方面的研究，所以想学习学习，谢谢啊！

**Comment by andyweiqiu** [comment]
> > > 你好！可以参考一下你的静态库(.a)文件吗？
> > > 谢谢啊！
> > 
> > 
> > 你是想要参考源代码吗？
> 
> 嗯嗯，是的，目前我也在做这方面的研究，所以想学习学习，谢谢啊！

不好意思啊，可能目前还不方便透漏，里面涉及到一些隐私，后面会考虑开源。不过可以跟你分享实现的方法

**Comment by LqNoob** [comment]
真的很谢谢您的回复！
 目前，kaldi的动态库文件我已经编译好了，主要是想使用其中的译码模块，但是我不知道如何去编写调用该模块的程序，所以请教一下！

**Comment by LqNoob** [comment]
> > 真的很谢谢您的回复！
> > 目前，kaldi的动态库文件我已经编译好了，主要是想使用其中的译码模块，但是我不知道如何去编写调用该模块的程序，所以请教一下！
> 
> 编译动态库给外部调用，我还没实现过。我目前主要的做法是，在服务端开启了一个解码器的服务，由客户端传输音频到服务端进行解码，再将结果返回。如果你使用的不是这种方式，我可能帮不到您，有时间我也去研究你这种实现方式

 原来你是在线识别的方式，我主要是想做离线情况下的识别，目前这方面的资料太少了，步履艰难。
 不过，还是谢谢您的耐心解答！
